**10개의 양수로 된 간단한 numpy 배열 만들기**

In [ ]:
import numpy as np

numbers = np.array(range(1,11), copy=True)
numbers


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

**ones()->1,zeros()->0,empty() ->아직 생성되지 않은 엔트리로 구성 <br>**
https://numpy.org/doc/stable/reference/generated/numpy.array.html


In [ ]:
#아직 생성되지 않은 엔트리로 구성된 배열을 1로 채움
ones = np.ones([2,4], dtype=np.float64) # 2개 로우 4개 값
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
#아직 생성되지 않은 엔트리로 구성된 배열을 0로 채움

zeros = np.zeros([2,4], dtype=np.float64)
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
#아직 생성되지 않은 엔트리로 구성된 배열
empty = np.empty([2,4],dtype=np.float64)
empty

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

**데이터 확인하기**

In [ ]:
ones.shape

(2, 4)

In [ ]:
ones.ndim # 배열의 차원 (2차원)

2

In [ ]:
ones.dtype # ones의데이터 타입

dtype('float64')

In [ ]:
numbers.dtype

dtype('int64')

**arange(start, stop, step, dtype=None) 일정 간격으로 배열 생성하는 함수**

In [ ]:
np_numbers = np.arange(2,5,0.25)
np_numbers


array([2.  , 2.25, 2.5 , 2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 ,
       4.75])

**astype(dtype,casting ="unsafe",copy = True)
아이템의 타입 변경해 주는 함수**

In [ ]:
np_numbers.dtype

dtype('int64')

In [ ]:
np_numbers =np_numbers.astype(np.int)
np_numbers.dtype

dtype('int64')

**reshape(d0,d1,...)대상 배열의 모양을 바꿔주는 함수**

In [ ]:
# 몇 가지 S&P 주식 기호들

sap = np.array(["MMM", "ABT", "ABBV", "ACN", "ACE", "ATVI", "ADBE", "ADT"])
sap #U4 는 4글자 유니코드


array(['MMM', 'ABT', 'ABBV', 'ACN', 'ACE', 'ATVI', 'ADBE', 'ADT'],
      dtype='<U4')

In [ ]:
sap.shape

(8,)

In [ ]:
sqp2d = sap.reshape(2,4)
sqp2d

array([['MMM', 'ABT', 'ABBV', 'ACN'],
       ['ACE', 'ATVI', 'ADBE', 'ADT']], dtype='<U4')

In [ ]:
# 기존 배열과 새로운 배열의 아이템의 개수는 항상 동일 해야 함
# numpy 보존의 법칙 성립

saq3d = sap.reshape(2, 2, 2) # 3차원으로 변경 콤마로 차원 체크 EX 콤마3개면 3차원
saq3d

array([[['MMM', 'ABT'],
        ['ABBV', 'ACN']],

       [['ACE', 'ATVI'],
        ['ADBE', 'ADT']]], dtype='<U4')

In [ ]:
saq3d[0]  #1차원



array([['MMM', 'ABT'],
       ['ABBV', 'ACN']], dtype='<U4')

In [ ]:
saq3d[1] #2차원

array([['ACE', 'ATVI'],
       ['ADBE', 'ADT']], dtype='<U4')

In [ ]:
saq3d[2] # 3차원 -> 없음 우리눈으로 알아보기 힘듬

IndexError: ignored

**데이터 클리닝(data cleaning)을 위해 사용 되는 boolean indexing
** 


In [ ]:
# 절대 음수 값이 와서는 안되는 데이터셋

dirty = np.array([9,4,1,-0.01,-0.02,-0.001])
whos_dirty = dirty < 0  # boolean indexing
whos_dirty 

array([False, False, False,  True,  True,  True])

In [ ]:
dirty[whos_dirty] = 0 # 모든 음수값을 0으로 바꿈
dirty

array([9., 4., 1., 0., 0., 0.])

**논리 연산자 | or, & and, - not 결합하여 boolean indexing 사용
**

In [ ]:
linear = np.arange(-1,1.1,0.2)
linear

array([-1.00000000e+00, -8.00000000e-01, -6.00000000e-01, -4.00000000e-01,
       -2.00000000e-01, -2.22044605e-16,  2.00000000e-01,  4.00000000e-01,
        6.00000000e-01,  8.00000000e-01,  1.00000000e+00])

In [ ]:
#-0.5~0.5 사이의 값만 ->0 변경하고 싶음

whos_linear = (linear <= 0.5) & (linear >= -0.5) #괄호 친 애들을 먼저 계산해줌
whos_linear 


array([False, False, False,  True,  True,  True,  True,  True, False,
       False, False])

In [ ]:
linear[whos_linear] = 0
linear

array([-1. , -0.8, -0.6,  0. ,  0. ,  0. ,  0. ,  0. ,  0.6,  0.8,  1. ])

**스마트 인덱싱**

In [ ]:
sap

array(['MMM', 'ABT', 'ABBV', 'ACN', 'ACE', 'ATVI', 'ADBE', 'ADT'],
      dtype='<U4')

In [ ]:
#s&p 리스트에서 두번쨰,세번째, 마지막 주식 기호를 추출

sap[[1,2,-1]]

array(['ABT', 'ABBV', 'ADT'], dtype='<U4')

In [ ]:
sqp2d

array([['MMM', 'ABT', 'ABBV', 'ACN'],
       ['ACE', 'ATVI', 'ADBE', 'ADT']], dtype='<U4')

In [ ]:
sqp2d[: ,[1]]

array([['ABT'],
       ['ATVI']], dtype='<U4')

In [ ]:
sqp2d[: , 1]

array(['ABT', 'ATVI'], dtype='<U4')

**차원만 같다면 numpy에서는 사칙연산 가능(그냥 더하기) -> 브로드캐스팅**

In [ ]:
a = np.arange(4)
b = np.arange(1,5)

print(a)
print(b)

[0 1 2 3]
[1 2 3 4]


In [ ]:
a+b

array([1, 3, 5, 7])

In [ ]:
a * 5

array([ 0,  5, 10, 15])

In [ ]:
noise = np.eye(4) 
noise

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
noise = np.eye(4) + 0.01 * np.random.random([4,4])
noise

array([[1.00902248e+00, 9.86512417e-04, 1.08591452e-03, 2.18646680e-03],
       [3.46118286e-03, 1.00759176e+00, 7.85534982e-03, 6.18874212e-03],
       [5.85808382e-03, 7.78004865e-03, 1.00257178e+00, 6.04036370e-03],
       [5.16088733e-03, 6.93068377e-04, 7.72266425e-03, 1.00339731e+00]])